### ISSUE TITLE
Problem in running api-sanity-checker on Windows

### ISSUE THREAD

**Issue by anurag029** [lvc/api-sanity-checker#13]
While running api-sanity-checker 1.98.2 on Windows7 with all the pre-requisites being installed, ERROR: can't compile header(s) is coming while generating the tests. Below is the log file entry:
<i>
Temporary header file 'C:\Users\ANURAG~1.CHO\AppData\Local\Temp\JXCm5OQczO/dump1.h' with the following content will be compiled to create GCC translation unit dump:

  // add includes
  #include "c:/Path -to-library-headers/zlib-1.2.3-lib/include/zlib.h"
  #include "c:/Path -to-library-headers/zlib-1.2.3-lib/include/zconf.h"

The GCC parameters:
  gcc -fdump-translation-unit -fkeep-inline-functions -c -x c++-header -D__thiscall=**attribute**((**thiscall**)) -DSORTPP_PASS -D__ptr64=" " -D__nullterminated=" " -D__uuidof(x)=IID() -D__w64=" " -D_USE_DECLSPECS_FOR_SAL -D__int32=int -D__int64="long long" -D__declspec(x)=**attribute**((x)) -D__inline=inline -D_cdecl=**attribute**((**cdecl**)) -D__int16=short -DDECLSPEC_DEPRECATED=" " -D_WIN32 -D__cdecl=**attribute**((**cdecl**)) -D__stdcall=**attribute**((**stdcall**)) -D__noop=" " -D__try= -D__forceinline=inline -D_M_IX86=300 -D__builtin_alignof(x)=**alignof**(x) -D_MSC_EXTENSIONS -D__fastcall=**attribute**((**fastcall**)) -D_MSC_VER=1500 -D_stdcall=**attribute**((**stdcall**)) -D__except(x)= -DSECURITY_WIN32 -D_inline=inline -D__nullnullterminated=" " -D_fastcall=**attribute**((**fastcall**)) -D__pragma(x)= -D__int8=char -D__forceinline=**inline -D__possibly_notnullterminated=" " -DSHSTDAPI_(x)=x -D_thiscall=__attribute**((**thiscall**)) -D_STDCALL_SUPPORTED -D__ptr32=" " -fpermissive -w "C:\Users\ANURAG~1.CHO\AppData\Local\Temp\JXCm5OQczO/dump1.h"

gcc: error: CreateProcess: No such file or directory

</i>
Please help. 

Thanks!!

**Comment by shreyas-m791** [comment]
Can anyone please provide complete instructions to setup and use api-sanity-checker on Windows 10 using MinGW or any other tool?

**Comment by bsdhw** [comment]
See https://github.com/lvc/api-sanity-checker/issues/33#issuecomment-671523795
