### ISSUE TITLE
ERROR: prefix is not absolute path

### ISSUE THREAD

**Issue by nikcruise007** [lvc/api-sanity-checker#23]
Hi,
 Can you please guide me here to identify the mistake while installation. 

Error:
qabuilder@qabuilder:~/Desktop/api-tester/api-sanity-checker$ sudo make install prefix=/usr
perl Makefile.pl -install -prefix "/usr"
INSTALL PREFIX: /usr
-- Installing /usr/bin/api-sanity-checker
-- Installing /usr/share/api-sanity-checker
qabuilder@qabuilder:~/Desktop/api-tester/api-sanity-checker$ sudo make install prefix=PREFIX [/usr, /usr/local]
perl Makefile.pl -install -prefix "PREFIX"
ERROR: prefix is not absolute path
make: *** [install] Error 1
qabuilder@qabuilder:~/Desktop/api-tester/api-sanity-checker$ cd ..
qabuilder@qabuilder:~/Desktop/api-tester$ sudo make install prefix=PREFIX [/usr, /usr/local]
make: *** No rule to make target `install'.  Stop.
qabuilder@qabuilder:~/Desktop/api-tester$ echo $PREFIX

qabuilder@qabuilder:~/Desktop/api-tester$ sudo cd /s

Is PREFIX an enviroment variable ? if so what data should i store inside it. 

My folder structure is , 
qabuilder@qabuilder:/$ ls
bin  boot  cdrom  dev  etc  home  initrd.img  initrd.img.old  lib  lib32  lib64  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old

Thanking in advance,
Nikesh

**Comment by lvc** [comment]
Hello,

PREFIX is the path prefix where to install the tool. The tool files will be installed to PREFIX/bin and PREFIX/share directories.

The most common PREFIX is /usr:

    sudo make install prefix=/usr

Thank you.
