### ISSUE TITLE
seeing tests failures, is this an issue in my setup ?

### ISSUE THREAD

**Issue by nikcruise007** [lvc/api-sanity-checker#24]
Following the steps:
$ wget https://github.com/downloads/lvc/api-sanity-checker/api-sanity-checker-1.12.10.tar.gz
$ tar -xzf api-sanity-checker-1.12.10.tar.gz
$ cd api-sanity-checker-1.12.10
$ sudo perl Makefile.pl -install --prefix=/usr
$ cd tmp/
$ api-sanity-checker -test

Got the result like this,
qabuilder@qabuilder:/tmp$ api-sanity-checker -test

testing C library API
library(ies) analysis: [100.00%]
header(s) analysis: [25.00%]
Using C99 compatibility mode
header(s) analysis: [100.00%]
generating tests: 9/9 [100.00%], success/fail: 9/0    
1. see generated test suite in the directory 'tests/libsample_c/1.0/'
2. for viewing the tests use 'tests/libsample_c/1.0/view_tests.html'
3. use -build option for building tests
building tests: 9/9 [100.00%], success/fail: 9/0    
running tests: 9/9 [100.00%], success/fail: 8/1    
creating report ...
see test results in the file:
  test_results/libsample_c/1.0/test_results.html
result: SUCCESS (9 test cases, 8 passed, 1 failed)

testing C++ library API
library(ies) analysis: [100.00%]
header(s) analysis: [100.00%]
generating tests: 24/24 [100.00%], success/fail: 24/0    
1. see generated test suite in the directory 'tests/libsample_cpp/1.0/'
2. for viewing the tests use 'tests/libsample_cpp/1.0/view_tests.html'
3. use -build option for building tests
building tests: 24/24 [100.00%], success/fail: 24/0    
running tests: 24/24 [100.00%], success/fail: 23/1    
creating report ...
see test results in the file:
  test_results/libsample_cpp/1.0/test_results.html
result: SUCCESS (24 test cases, 23 passed, 1 failed)

Am seeing a failure in the check test. 

please rename to .html to view Tests_result_*.txt 

[test_results_c.txt](https://github.com/lvc/api-sanity-checker/files/330298/test_results_c.txt)
[test_results_cpp.txt](https://github.com/lvc/api-sanity-checker/files/330299/test_results_cpp.txt)

**Comment by lvc** [comment]
Hello,

This is OK. One test case should crash in order to make sure that the tool can catch crashes.

Also please use latest 1.98.7 version of the tool instead of 1.12.10.

Thank you.
